<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
          crossorigin="anonymous"/>
    <link href="components/styles.css" rel="stylesheet" type="text/css"/>
    <script src="components/header_guest.js" type="text/javascript" defer></script>
    <script src="components/footer.js" type="text/javascript" defer></script>
</head>
<body>
<header-component></header-component>
<main>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #f1f1f1;
        }

        * {
            box-sizing: border-box;
        }

        .container {
            padding: 16px;
            background-color: white;
        }

        input[type=text], input[type=password], input[type=number] {
            width: 100%;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f1f1f1;
        }

        input[type=text]:focus, input[type=password]:focus {
            background-color: #ddd;
            outline: none;
        }


        .registerbtn {
            background-color: #175581;
            color: white;
            padding: 16px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
            opacity: 0.9;
        }

        .registerbtn:hover {
            opacity: 1;
        }

        a {
            color: dodgerblue;
        }

        .signin {
            background-color: #f1f1f1;
            text-align: center;
        }
    </style>
    </head>
    <body>

    <div class="container">
        <h1>Register</h1>
        <p>Please fill in this form to create an account.</p>

        <form action="/Register/studentRegistration" method="post" style='width:900px'>

            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="Enter email" name="email" id="email" required>

            <label for="first-name"><b>First name</b></label>
            <input type="text" placeholder="First name" name="first-name" id="first-name" required>

            <label for="last-name"><b>Last name</b></label>
            <input type="text" placeholder="Last name" name="last-name" id="last-name" required>

            <label for="grade"><b>Grade</b></label>
            <input type="number" placeholder="Grade" name="grade" id="grade" required>

            <label for="psw"><b>Password</b></label>
            <input type="password" placeholder="Enter password" name="password" id="password" required>

            <label for="password-repeat"><b>Repeat Password</b></label>
            <input type="password" placeholder="Repeat password" name="password-repeat" id="password-repeat" required>

            <button type="submit" class="registerbtn">Register</button>

        </form>
    </div>
    <div class="container signin">
        <p>Already have an account? <a href="/Login">Login</a></p>
    </div>
</main>
<footer-component></footer-component>
</body>
<html>