<main>
    <link href="../components/dictionary.css" rel="stylesheet" type="text/css"/>
    <div class="wrapper">
        <audio id="sound"></audio>
        <div class="container">
            <div class="search-box">
                <input type="text" placeholder="Type the word here..." id="inp-word"/>
                <button id="search-btn" class="btn">Search</button>
            </div>
            <div id="result" class="result"></div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        const result = document.getElementById("result");
        const sound = document.getElementById("sound");

        const btn = document.getElementById("search-btn");
        btn.addEventListener("click", () => {
            let word = document.getElementById("inp-word").value;
            var data = 'word=' + word;
            $.ajax({
                type: "POST",
                url: "/Dictionary/searchWord",
                data: data,
                cache: false,
                success: function (data) {
                    try {
                        var array = JSON.parse(data);
                        result.innerHTML = `
  <div class="word">
    <h3>${array[0]}</h3>
    <button onclick="playSound()"> <i class="fas fa-volume-up"></i></button>
  </div>
  <div class="details">
    <p>${array[1]}</p>
    <p>/${array[2]}/</p>
  </div>
  <p class="word-meaning">
    ${array[3]}
  </p>
  <p class="word-example">${
                            array[4] || ""
                        }</p>
  `;
                        sound.setAttribute("src", `https:${array[5]}`);
                    } catch (e) {
                        result.innerHTML = `<h3 class="error">Couldn't Find The Word!</h3>`;
                    }
                }
            });
        })

        function playSound() {
            sound.play();
        }
    </script>
</main>