<main>
    <h1>Welcome to Test Explore, <?php echo $this->username?></h1>
    <h2>System for creating and taking tests</h2>
    <div class="row">
        <div class="column">
            <img class="icon" src="../img/accessability.png" alt="test" />
            <h2>Accessibility</h2>
            <p>Test Explore is easy to use and no prior training is required.
                Each student has access to preparatory tests of teachers from all over the country</p>
        </div>
        <div class="column">
            <img class="icon" src="../img/mark.png" alt="test" />
            <h2>Automatic evaluation</h2>
            <p>The tests are graded automatically, allowing students to understand
                their results immediately after the test</p>
        </div>
        <div class="column">
            <img class="icon" src="../img/generating.png" alt="test" />
            <h2>Generating</h2>
            <p>Test Explore allows easy creation of public and private tests by teachers.
                They will be generated automatically to be different at each solution</p>
        </div>
    </div>
</main>