<main>
    <div class="container">
        <h1>Register</h1>
        <p>Please fill in this form to create an account.</p>

        <form action="/Register/studentRegistration" method="post" style='width:900px'>

            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="Enter email" name="email" id="email" required>

            <label for="first-name"><b>First name</b></label>
            <input type="text" placeholder="First name" name="first-name" id="first-name" required>

            <label for="last-name"><b>Last name</b></label>
            <input type="text" placeholder="Last name" name="last-name" id="last-name" required>

            <label for="grade"><b>Grade</b></label>
            <input type="number" placeholder="Grade" name="grade" id="grade" required>

            <label for="psw"><b>Password</b></label>
            <input type="password" placeholder="Enter password" name="password" id="password" required>

            <label for="password-repeat"><b>Repeat Password</b></label>
            <input type="password" placeholder="Repeat password" name="password-repeat" id="password-repeat" required>

            <button type="submit" class="registerbtn">Register</button>

        </form>
    </div>
    <div class="container signin">
        <p>Already have an account? <a href="../index.php">Login</a></p>
    </div>
</main>