<main>
    <link href="../components/student_exams.css" rel="stylesheet" type="text/css"/>

    <table>
        <tr>
            <th>Exam Name</th>
            <th>Level</th>
            <th>Access Code</th>
            <th>Teacher</th>
        </tr>
        <?php

        foreach ($this->exams as $exam) {
            echo "<tr>";
            echo "<td>" . $exam->getName() . "</td>";
            echo "<td>" . $exam->getLevel() . "</td>";
            echo "<td>" . $exam->getAccessCode() . "</td>";
            echo "<td>" . $exam->getTeacher()->getFullName() . "</td>";
            echo "</tr>";
        }
        ?>
    </table>
</main>