<main>
    <link href="../components/student_exams.css" rel="stylesheet" type="text/css"/>
        <form name="filter" action="/StudentExams/filterExams" method="post">
            <div class="container-left">
                <div class="type">
                    <img src="../img/student.png" alt="teacher" width="100"/>
                    <h1>SUBJECTS</h1>
                    <div class="bump">
                        <div class="box1">
                            <input type="checkbox" id="literature" name="literature" value="Literature">
                            <label for="literature" class="check-box"></label>
                            <h4>Literature</h4>
                        </div>
                        <div class="box1">
                            <input type="checkbox" id="mathematics" name="mathematics" value="Mathematics">
                            <label for="mathematics" class="check-box"></label>
                            <h4>Mathematics</h4>
                        </div>
                        <div class="box1">
                            <input type="checkbox" id="geography" name="geography" value="Geography">
                            <label for="geography" class="check-box"></label>
                            <h4>Geography</h4>
                        </div>
                        <div class="box1">
                            <input type="checkbox" id="history" name="history" value="History">
                            <label for="history" class="check-box"></label>
                            <h4>History</h4>
                        </div>
                        <div class="box1">
                            <input type="checkbox" id="science" name="science" value="Science">
                            <label for="science" class="check-box"></label>
                            <h4>Science</h4>
                        </div>
                    </div>
                </div>
                <div class="sortBy">
                    <h1>SORT BY</h1>
                    <select class="sort-control" name="sort-control" id="sort-control">
                        <option value="0" selected disabled hidden>Choose sorting options</option>
                        <option value="1">Date of creation [Oldest to Newest]</option>
                        <option value="2">Date of creation [Newest to Oldest]</option>
                        <option value="3">Teacher name [A to Z]</option>
                        <option value="4">Level [Аscending order]</option>
                        <option value="5">Level [Descending order]</option>
                    </select>
                    <input type="submit" value="Apply filters" id="filter-button">
                </div>

            </div>
        </form>

        <div class="table-exams">
            <h1>EXAMS</h1>
            <table>
                <tr>
                    <th>Exam Name</th>
                    <th>Level</th>
                    <th>Access Code</th>
                    <th>Created</th>
                    <th>Teacher</th>
                    <th>Actions</th>
                </tr>
        </div>
        <?php

        foreach ($this->exams as $exam) {
            echo "<tr>";
            echo "<td>" . $exam->getName() . "</td>";
            echo "<td>" . $exam->getLevel() . "</td>";
            echo "<td>" . $exam->getAccessCode() . "</td>";
            echo "<td>" . $exam->getDateOfCreation() . "</td>";
            echo "<td>" . $exam->getTeacher()->getFullName() . "</td>";
            echo "<td> <form class='start-button' name='edit-exam' action='/TakeExam/getexam' method='post'><input class='start-button-input' type='submit' value='Start' id='take-exam'></form></td>";
            echo "</tr>";
        }
        ?>
    </table>

</main>