<main>
    <link href="../components/student_exams.css" rel="stylesheet" type="text/css"/>
        <form name="filter" action="/StudentExams/filterExams" method="post">
            <div class="container-left">
                <div class="type">
                    <img src="../img/student.png" alt="teacher" width="100"/>
                    <h1>SUBJECTS</h1>
                    <div class="bump">
                        <div class="box1">
                            <input type="checkbox" id="literature" name="literature" value="Literature">
                            <label for="literature" class="check-box"></label>
                            <h4>Literature</h4>
                        </div>
                        <div class="box1">
                            <input type="checkbox" id="mathematics" name="mathematics" value="Mathematics">
                            <label for="mathematics" class="check-box"></label>
                            <h4>Mathematics</h4>
                        </div>
                        <div class="box1">
                            <input type="checkbox" id="geography" name="geography" value="Geography">
                            <label for="geography" class="check-box"></label>
                            <h4>Geography</h4>
                        </div>
                        <div class="box1">
                            <input type="checkbox" id="history" name="history" value="History">
                            <label for="history" class="check-box"></label>
                            <h4>History</h4>
                        </div>
                        <div class="box1">
                            <input type="checkbox" id="science" name="science" value="Science">
                            <label for="science" class="check-box"></label>
                            <h4>Science</h4>
                        </div>
                    </div>
                </div>
                <div class="sortBy">
                    <h1>SORT BY</h1>
                    <select class="sort-control" name="sort-control" id="sort-control">
                        <option value="0" selected disabled hidden>Choose sorting options</option>
                        <option value="1">Date of creation [Oldest to Newest]</option>
                        <option value="2">Date of creation [Newest to Oldest]</option>
                        <option value="3">Teacher name [A to Z]</option>
                        <option value="4">Level [Аscending order]</option>
                        <option value="5">Level [Descending order]</option>
                    </select>
                    <input type="submit" value="Apply filters" id="filter-button">
                </div>

            </div>
        </form>

        <div class="table-exams">
            <h1>EXAMS</h1>
            <table>
                <tr>
                    <th>Exam Name</th>
                    <th>Level</th>
                    <th>Access Code</th>
                    <th>Created</th>
                    <th>Teacher</th>
                    <th>Actions</th>
                </tr>
        </div>
        <?php

        foreach ($this->exams as $exam) {
            echo "<tr>";
            echo "<td>" . $exam->getName() . "</td>";
            echo "<td>" . $exam->getLevel() . "</td>";
            echo "<td>" . $exam->getAccessCode() . "</td>";
            echo "<td>" . $exam->getDateOfCreation() . "</td>";
            echo "<td>" . $exam->getTeacher()->getFullName() . "</td>";
            echo "<td> <button class='start-button start-button-input start-exam'  id='start-exam-" . $exam->id . "'>Start</button>  </td>";
            echo "</tr>";
        }
        ?>
    </table>

    <!-- The Upload Modal -->
    <div id="myModal" class="modal">

        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <form class='start-button' action='/TakeExam/' method='post'>
                <input type='hidden' id="exam-id" name='exam-id'>
                <label for="exam-access-code">Access Code (if any):</label>
                <input id="exam-access-code" type='text' name='exam-access-code'>
                <input class='start-button-input' type='submit' value='Start' id='take-exam'>
        </div>

    </div>

    <script>
        var modal = document.getElementById("myModal");
        var btnList = document.getElementsByClassName("start-exam");
        var span = document.getElementsByClassName("close")[0];

        for (let i = 0; i < btnList.length; i++) {
            btnList[i].onclick = function() {
                modal.style.display = "block";
                var btnId = btnList[i].id;
                var examId = btnId.split("-")[2];
                var hiddenLabel = document.getElementsByClassName("exam-id");
                hiddenLabel.value = examId;
            }
        }

        span.onclick = function() {
            modal.style.display = "none";
        }

        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>
</main>