<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=qFqE_K7pUKhAq16cqdkZPf9XBfwqEQVx0LiAFgKoKdNaQJbR_LJkVSRnVVc55uN_6RkxMAM8jyRfsmW_9b3NKTpuGYK4RrvolBmWHLxFXs7-Fx1OFdCQNjzYO_DrFIMr-0gzhZtwh1-JKml-c6j3uy9GFtveymvtCbLwBLLCP6ZXyq8dQP5OxP61tjO-vXrd_1vRFWDYqP39XyY5dbJkd0EtHVjVwPpGgfT6INRtbg58v8uvzUPzA75IO6z_yeObmBdE-LWqCjiwDWdyxeOKihloEFY1WULIJNAt-1eIfCfwB5klD2YF5qi2XSYoL6p5ucwTzCGL0TUcLAIgCrTBHaq9vs_8Lwo3AFJ6Yy8GaHA" charset="UTF-8"></script><style>
        body{
            background-color: #add8e6;
        }

        .image-container {
            height: 550px;
            position: relative;
        }

        img {
            width: 60%;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        h1{
            font-size: 50px;
            text-align: center;
            padding-bottom: 20px;
            color: #02B5FF;
            font-weight: bold;
            text-shadow: 2px 2px 1px white;
        }

        a{
            text-decoration: none;
        }
    </style>
</head>
<body>
<main>
    <div class="image-container">
        <img src="/img/error.png" alt="error-image" />
    </div>
    <a href="/Home"><h1>GO TO HOMEPAGE</h1></a>
</main>
</body>
</html>